name: Update currency JSON every 12h
on:
  schedule:
    - cron: "0 */12 * * *"   # every 12 hours (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch latest rates from exchangeratesapi.io
        env:
          API_KEY: ${{ secrets.FREECURRENCYAPI_KEY }}
        run: |
          python3 - <<'PY'
          import json, os, sys, urllib.request, time

          api_key = os.environ["API_KEY"]
          url = f"https://api.exchangeratesapi.io/v1/latest?access_key={api_key}&base=USD"

          try:
              with urllib.request.urlopen(url, timeout=30) as r:
                  src = json.load(r)
          except Exception as e:
              print("ERROR: failed to fetch API:", e, file=sys.stderr)
              sys.exit(1)

          if not src.get("success") or "rates" not in src:
              print("ERROR: API returned non-success or missing rates", file=sys.stderr)
              print(json.dumps(src, indent=2))
              sys.exit(1)

          # Convert to target format
          out = {
              "data": src["rates"],
              "updated_at_unix": int(src.get("timestamp", int(time.time())))
          }

          with open("data.json", "w", encoding="utf-8") as f:
              json.dump(out, f, ensure_ascii=False, indent=2)
          PY

      - name: Commit & push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if git diff --quiet; then
            echo "No changes"
          else
            git add data.json
            git commit -m "chore: update data.json ($(date -u +%FT%TZ))"
            git push
          fi
