name: Update currency JSON hourly
on:
  schedule:
    - cron: "5 * * * *" # once per hour at :05
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch latest rates
        env:
          API_KEY: ${{ secrets.FREECURRENCYAPI_KEY }}
        run: |
          python3 - <<'PY'
          import json, os, sys, urllib.request
          api_key = os.environ["API_KEY"]
          url = f"https://api.freecurrencyapi.com/v1/latest?apikey={api_key}"
          with urllib.request.urlopen(url) as r:
              payload = json.load(r)
          # payload looks like: {"data": { "AED": 3.67, ... }}
          # You can transform if needed; here we keep as-is but add a timestamp:
          from time import time
          payload["updated_at_unix"] = int(time())
          open("data.json", "w", encoding="utf-8").write(
              json.dumps(payload, ensure_ascii=False, indent=2)
          )
          PY

      - name: Commit & push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if git diff --quiet; then
            echo "No changes"
          else
            git add data.json
            git commit -m "chore: update data.json ($(date -u +%FT%TZ))"
            git push
          fi
